### ISSUE TITLE
Ignore whitespace when parsing element content.

### ISSUE THREAD

**Issue by lukasgeyer** [lukasgeyer/launcher#1]
Whitespace shall be ignored at the beginning and the end of element content, so it can be used to structure the document.

**Comment by dimescc** [comment]
very low prio! Config files already changed! All PT projects and Products are able to be imported! Files PSP.xml at 7400 (Workspace)

**Comment by dimescc** [comment]
_Removed as it may contain sensitive information._

**Comment by dimescc** [comment]
[launcher.txt](https://github.com/lukasgeyer/launcher/files/248540/launcher.txt)
-> change to launcher.xml necessary
